### ISSUE TITLE
サーバーのインフラ構築

### ISSUE THREAD

**Issue by sisisin** [opt-tech/chattun#12]
### chattunのサーバーサイドで必要な機能要件

- OAuth認可機能
- `@slack/client`のRTMClientから受け取ったEventをwebsocketでフロントに通知する機能
- 静的ファイルの配信
  - 今の所フロントもサーバーもCORS入れたりして別環境で動かせるようにはなってるので、フロント配信のことは考えずに構築でいいはず
  - [netlify](https://www.netlify.com/)が便利そう

### サーバーアプリケーションでの非機能要件

- Node.jsサーバー
  - 使うライブラリ的に。
- セッション保持
  - node.jsはシングルスレッドのため、いずれかのリクエストで例外がでて死んだ場合、他のクライアントとの接続も全て死ぬ。そのため、websocketのconnectionの復旧手段が必要（KVSかRDBにslackのuser_idからOAuthトークンを復元できれば良いはず）

### やりそうな作業

- 本番環境の構築
- 誰かが書いたアプリコードを本番環境で動くように調整
  - 環境変数とかKVS/RDBとのconnection情報とか

**Comment by sisisin** [comment]
### 必要な構築

# サーバーサイド
- node.jsサーバー
- Redis

# フロントエンド

静的ファイル配信環境
- S3,netlifyあたり


### 作業

- 上記環境を構築・デプロイ可能な状態にする
- ミドルウェアとの接続情報がローカル環境ようにハードコードされているので、これを環境変数などで本番環境・ローカル環境の差し替えが可能なようにする

**Comment by sisisin** [comment]
デプロイすべきもの

# server

- devDependenciesを覗いた分だけをインストールするオプション付きで `yarn install` したアプリを `yarn start`できれば良い（herokuなら基本何もしなくていい）

# front

`yarn build`して、 `dist`が出来るので、この中身すべて

**Comment by Schwertgewehr** [comment]
<details>
<summary>自分メモ</summary>
```
> Node.jsサーバー
  使うライブラリ的に。
slack の sdk が npm にある

socket.io がある 


- デプロイのしくみ
- デプロイすれば動く状態
- ts 使うはずなのでビルド

- 動くとは
  - パブリック？


上記環境を構築 -> ポチポチ

ミドルウェアとの接続情報がローカル環境ようにハードコードされているので、これを環境変数などで本番環境・ローカル環境の差し替えが可能なようにする

インフラの予算
heroku でも Redis
```
</details>

**Comment by Schwertgewehr** [comment]
<details>
<summary>README</summary>

```
$ brew install heroku/brew/heroku
```
</details>

**Comment by Schwertgewehr** [comment]
<details>
<summary>infra</summary>

```bash
$ heroku create
Creating app... done, ⬢ calm-thicket-83425
https://calm-thicket-83425.herokuapp.com/ | https://git.heroku.com/calm-thicket-83425.git
```
</details>
