### ISSUE TITLE
小さいウィンドウサイズでもロゴが中央に来るように

### ISSUE THREAD

**Issue by tokkiyaa** [opt-tech/chattun#132]
https://gyazo.com/5809fcefb86793d4afa04a4eec70d68d

nativefier とかでアプリ化した時に使いやすくしてほしいかも

**Comment by naru0504** [comment]
画像は`nativefier`を利用した際のものですかね？
Chromeでは再現できていない（中央揃っている）ので、後ほど詳細お教えいただけたらと思います。

**Comment by tokkiyaa** [comment]
あ、`nativefier` 利用時だけに発生するっぽいですね。
失礼しました
